version: '3'

services:
  app:
    build: .
    container_name: url-shortener-app
    command: uvicorn app.api:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
    environment:
      - DATABASE_URL=postgresql://user:password@db/urlshortener
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq//

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: "url_user"        
      POSTGRES_PASSWORD: "strongpassword123"  
      POSTGRES_DB: "url_shortener_db"   
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  celery:
    build: .
    container_name: url-shortener-celery
    command: celery -A app.tasks.celery_app worker --loglevel=info
    depends_on:
      - rabbitmq
      - db
    environment:
      - DATABASE_URL=postgresql://url_user:strongpassword123@db:5432/url_shortener_db
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq//

volumes:
  db_data:
